# Generated by Django 4.1.7 on 2023-04-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_produtos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='listas.lista'),
        ),
    ]
